FROM opensuse/tumbleweed

RUN zypper --gpg-auto-import-keys refresh
RUN zypper install -y openssh vim iputils ruby2.7 ruby2.7-devel ruby2.7-rubygem-cheetah ruby2.7-rubygem-nokogiri 
RUN gem install git_diff_parser dry-cli

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
